services:
  careers:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .docker.env
    environment:
      MONGO_URI: mongodb://mongoDB:27017/careers
    depends_on:
      - mongoDB
      - minio

  mongoDB:
    image: mongo:5.0
    container_name: mongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    command: server /data

volumes:
  mongodb_data:
  minio_data:


